import type { NextPage } from "next";
import { signIn, useSession, getSession } from "next-auth/react";
import Head from "next/head";
import { prisma } from "../server/db";
import { trpc } from "../utils/trpc";
import usePosts from "../hooks/use-posts";
import { useEffect } from "react";

const Home: NextPage = () => {
  const thing = usePosts();
  (async () => {
    const user = useSession();
  })();

  // async () => {
  //   prisma.post.create({
  //     data: {
  //       title: "Hello World",
  //       content: "This is my first post",
  //       authorId: user,
  //     },
  //   });
  // };
  console.log(thing);

  return (
    <>
      <Head>
        <title>Create t3 App</title>
        <meta name="description" content="Generated by create t3 app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* {data?.map((post) => (
          <div key={post.id}>
            <h1>{post.title}</h1>
            <p>{post.content}</p>
          </div>
        ))} */}
        <h1>Create t3 App</h1>
        <button
          className="border-[1px] px-12 py-2 rounded-full"
          onClick={() => signIn("discord")}
        >
          Login with Discord
        </button>
      </main>
    </>
  );
};

export default Home;
