import { Session } from "next-auth";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

const Home = () => {
  const { status, data } = useSession();
  console.log(data?.user);

  return (
    <>
      <Head>
        <title>Create t3 App</title>
        <meta name="description" content="Generated by create t3 app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
};

export default Home;
